import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/app/Navbar";
import localFont from "next/font/local";

const clashGrotesk = localFont({
  src: [
    {
      path: "../public/font/ClashGrotesk-Regular.otf",
      style: "normal",
      weight: "400",
    },
    {
      path: "../public/font/ClashGrotesk-Medium.otf",
      style: "normal",
      weight: "500",
    },
    {
      path: "../public/font/ClashGrotesk-Semibold.otf",
      style: "normal",
      weight: "600",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={clashGrotesk.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
